site_name: Mastering Docker

docs_dir: website

site_author: Anand Chitpothu
copyright: Copyright © 2022-23, Pipal Academy

theme:
  name: material

nav:
  - The Course:
    - syllabus.md
  - Getting Started:
    - getting-started/lab-setup.md
    - getting-started/vim.md
  - Managing Servers:
    - session1.md
  - Docker:
    - docker/introduction.md
    - docker/registry.md
    - docker/environment.md
    - docker/ports.md
    - docker/volumes.md
    - docker/cheatsheet.md
    - docker/diving-in.md
    - docker/docker-compose.md
    - docker/optimizing-images.md
    # - docker/best-practices.md
  - Notes:
    - notes/session3.md
  - Assignments:
    - assignments/assignment-1.md
    - assignments/assignment-2.md
    - assignments/assignment-3.md
    - assignments/assignment-4.md

# plugins:
#   - autorefs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format